USE [master]
GO

/****** Object:  Database [dogBarberShopDB]    Script Date: 9/1/2020 1:28:36 PM ******/
CREATE DATABASE [dogBarberShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dogBarberShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dogBarberShopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dogBarberShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dogBarberShopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dogBarberShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dogBarberShopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dogBarberShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dogBarberShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dogBarberShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dogBarberShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET RECOVERY FULL 
GO

ALTER DATABASE [dogBarberShopDB] SET  MULTI_USER 
GO

ALTER DATABASE [dogBarberShopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dogBarberShopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dogBarberShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dogBarberShopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dogBarberShopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dogBarberShopDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dogBarberShopDB] SET  READ_WRITE 
GO


